export const LOAD_AUTH_FORM_START = 'LOAD_AUTH_FORM_START';
export const LOAD_AUTH_FORM_COMPLETE = 'LOAD_AUTH_FORM_COMPLETE';
export const LOAD_AUTH_FORM_FAIL = 'LOAD_AUTH_FORM_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
